apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: spring-cloud-demo
    role: api
    tier: backend
spec:
  ports:
    - port: 10000
      targetPort: 10000
  selector:
    app: spring-cloud-demo
    role: api
    tier: backend
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: api
  labels:
    app: spring-cloud-demo
    role: api
    tier: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-cloud-demo
        role: api
        tier: backend
    spec:
      containers:
      - image: node2:5000/spring-cloud-demo/some:1.0.0-SNAPSHOT
        name: some
        env:
          - name: CONFIG_HOST
            value: "config"
          - name: CONFIG_PORT
            value: "8888"
          - name: EUREKA_HOST
            value: "discovery"
          - name: EUREKA_PORT
            value: "8761"
          - name: SPRING_PROFILES_ACTIVE
            value: "pro"
        ports:
        - containerPort: 8083
      - image: node2:5000/spring-cloud-demo/person:1.0.0-SNAPSHOT
        name: person
        env:
          - name: CONFIG_HOST
            value: "config"
          - name: CONFIG_PORT
            value: "8888"
          - name: EUREKA_HOST
            value: "discovery"
          - name: EUREKA_PORT
            value: "8761"
          - name: SPRING_PROFILES_ACTIVE
            value: "pro"
        ports:
        - containerPort: 8082     
      - image: node2:5000/spring-cloud-demo/gateway:1.0.0-SNAPSHOT
        name: gateway
        env:
          - name: CONFIG_HOST
            value: "config"
          - name: CONFIG_PORT
            value: "8888"        
          - name: EUREKA_HOST
            value: "discovery"
          - name: EUREKA_PORT
            value: "8761"
          - name: SPRING_PROFILES_ACTIVE
            value: "pro"
        ports:
        - containerPort: 10000        