apiVersion: v1
kind: Service
metadata:
  name: config
  labels:
    app: spring-cloud-demo
    role: config
    tier: backend
spec:
  ports:
    - port: 8888
      targetPort: 8888
  selector:
    app: spring-cloud-demo
    role: config
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: config
  labels:
    app: spring-cloud-demo
    role: config
    tier: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-cloud-demo
        role: config
        tier: backend
    spec:
      containers:
      - image: node2:5000/spring-cloud-demo/config:1.0.0-SNAPSHOT
        name: config
        env:
          - name: EUREKA_HOST
            value: "discovery"
          - name: EUREKA_PORT
            value: "8761"
        ports:
        - containerPort: 8888