apiVersion: v1
kind: Service
metadata:
  name: discovery
  labels:
    app: spring-cloud-demo
    role: discovery
    tier: backend
spec:
  ports:
    - port: 8761
      targetPort: 8761
  selector:
    app: spring-cloud-demo
    role: discovery
    tier: backend  
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: discovery
  labels:
    app: spring-cloud-demo
    role: discovery
    tier: backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-cloud-demo
        role: discovery
        tier: backend        
    spec:
      containers:
      - image: node2:5000/spring-cloud-demo/discovery:1.0.0-SNAPSHOT
        name: discovery       
        ports:
        - containerPort: 8761