apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: spring-cloud-demo
spec:
  ports:
    - port: 3306
  selector:
    app: spring-cloud-demo
    tier: mysql
  #clusterIP: 192.168.3.2
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: spring-cloud-demo
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: spring-cloud-demo
        tier: mysql
    spec:
      containers:
      - image: index.tenxcloud.com/docker_library/mysql:5.6
        name: mysql
        env:
          # $ kubectl create secret generic mysql-pass --from-file=password.txt
          # make sure password.txt does not have a trailing newline
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password.txt
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        hostPath:
          path: /data/mysql
