apiVersion: v1
kind: Service
metadata:
  name: ui
  labels:
    app: spring-cloud-demo
    role: ui
    tier: frontend
spec:
  ports:
    - name: http-ui
      port: 80
      targetPort: 80
    - name: http-monitor
      port: 8989
      targetPort: 8989
  selector:
    app: spring-cloud-demo
    role: ui
    tier: frontend
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ui
  labels:
    app: spring-cloud-demo
    role: ui
    tier: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-cloud-demo
        role: ui
        tier: frontend
    spec:
      containers:
      - image: node2:5000/spring-cloud-demo/monitor:1.0.0-SNAPSHOT
        name: monitor
        env:
          - name: CONFIG_HOST
            value: "config"
          - name: CONFIG_PORT
            value: "8888"
          - name: EUREKA_HOST
            value: "discovery"
          - name: EUREKA_PORT
            value: "8761"
          - name: SPRING_PROFILES_ACTIVE
            value: "pro"
        ports:
        - containerPort: 8989
      - image: node2:5000/spring-cloud-demo/ui:1.0.0-SNAPSHOT
        name: ui
        env:
          - name: CONFIG_HOST
            value: "config"
          - name: CONFIG_PORT
            value: "8888"
          - name: EUREKA_HOST
            value: "discovery"
          - name: EUREKA_PORT
            value: "8761"
          - name: SPRING_PROFILES_ACTIVE
            value: "pro"
        ports:
        - containerPort: 80        