server:
  port: 8761
spring:
  application:
    name: discovery
eureka:
  instance:
    hostname: discovery
  client:
    register-with-eureka: false
    fetch-registry: false
debug: true
logging:
  file: ${spring.application.name}.log